# Generated by Django 3.1.3 on 2021-07-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
