# Generated by Django 3.1.3 on 2021-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src', '0002_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='file')),
                ('name', models.CharField(default='devesh', max_length=255)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
