# Generated by Django 3.1.3 on 2021-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20210716_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(default='hello.sg', max_length=255),
        ),
        migrations.AddField(
            model_name='files',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='devesh', max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
