# Generated by Django 3.1.3 on 2021-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20210716_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.CharField(default='devesh', max_length=255),
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.CharField(default='devesh', max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(default='devesh', max_length=255),
        ),
    ]
