# Generated by Django 3.1.3 on 2021-08-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20210721_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='age',
        ),
        migrations.RemoveField(
            model_name='files',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
    ]
